package generate

import (
	"testing"

	"github.com/go-logr/logr"
	"github.com/kyverno/kyverno/api/kyverno"
	kyvernov1 "github.com/kyverno/kyverno/api/kyverno/v1"
	kyvernov1beta1 "github.com/kyverno/kyverno/api/kyverno/v1beta1"
	"github.com/kyverno/kyverno/pkg/background/common"
	"github.com/kyverno/kyverno/pkg/clients/dclient"
	"gotest.tools/assert"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
)

func newDownstreamConfigMap(name, namespace string, labels map[string]string) *unstructured.Unstructured {
	cm := &unstructured.Unstructured{}
	cm.SetAPIVersion("v1")
	cm.SetKind("ConfigMap")
	cm.SetName(name)
	cm.SetNamespace(namespace)
	cm.SetLabels(labels)
	return cm
}

// TestGetDownstreams_CloneList verifies that getDownstreams correctly retrieves
// downstream resources that were generated by a cloneList rule. When a trigger
// resource (e.g. a Namespace) is deleted, only the downstream resources carrying
// that trigger's UID label should be returned for cleanup.
func TestGetDownstreams_CloneList(t *testing.T) {
	const (
		policyName     = "sync-configmaps"
		ruleName       = "clone-cms"
		triggerKind    = "Namespace"
		triggerName    = "test-namespace"
		targetNamespace = "target-ns"
	)

	triggerUID := types.UID("trigger-uid-abc")

	// downstreamLabels mimics the labels applied by ManageLabels / TriggerInfo
	// when a resource is generated from a cloneList rule.
	downstreamLabels := map[string]string{
		common.GeneratePolicyLabel:          policyName,
		common.GeneratePolicyNamespaceLabel: "",
		common.GenerateRuleLabel:            ruleName,
		kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
		common.GenerateTriggerUIDLabel:      string(triggerUID),
		common.GenerateTriggerNSLabel:       "",
		common.GenerateTriggerKindLabel:     triggerKind,
		common.GenerateTriggerGroupLabel:    "",
		common.GenerateTriggerVersionLabel:  "v1",
	}

	// Two downstream ConfigMaps cloned from two different source ConfigMaps
	// but both generated from the same trigger Namespace.
	cm1 := newDownstreamConfigMap("source-cm-1", targetNamespace, downstreamLabels)
	cm2 := newDownstreamConfigMap("source-cm-2", targetNamespace, downstreamLabels)

	scheme := runtime.NewScheme()
	gvrToListKind := map[schema.GroupVersionResource]string{
		{Group: "", Version: "v1", Resource: "configmaps"}: "ConfigMapList",
	}

	fakeClient, err := dclient.NewFakeClient(scheme, gvrToListKind, cm1, cm2)
	assert.NilError(t, err)
	fakeClient.SetDiscovery(dclient.NewFakeDiscoveryClient(nil))

	c := &GenerateController{
		client: fakeClient,
		log:    logr.Discard(),
	}

	ur := &kyvernov1beta1.UpdateRequest{
		Spec: kyvernov1beta1.UpdateRequestSpec{
			Policy:           policyName,
			Rule:             ruleName,
			DeleteDownstream: true,
			Resource: kyvernov1.ResourceSpec{
				APIVersion: "v1",
				Kind:       triggerKind,
				Name:       triggerName,
				UID:        triggerUID,
			},
		},
	}

	// Rule that clones all ConfigMaps matching a cloneList selector.
	rule := kyvernov1.Rule{
		Name: ruleName,
		Generation: kyvernov1.Generation{
			CloneList: kyvernov1.CloneList{
				Kinds: []string{"v1/ConfigMap"},
			},
		},
	}

	// Build the initial selector the same way handleNonPolicyChanges does
	// before delegating to getDownstreams.
	selector := map[string]string{
		common.GeneratePolicyLabel:          policyName,
		common.GeneratePolicyNamespaceLabel: "",
		common.GenerateRuleLabel:            ruleName,
		kyverno.LabelAppManagedBy:           kyverno.ValueKyvernoApp,
	}

	downstreams, err := c.getDownstreams(rule, selector, ur)
	assert.NilError(t, err)
	assert.Equal(t, 2, len(downstreams.Items))
}
